Vagrant.configure("2") do |config|

  config.vm.define "shellbash" do |shellbash|
    shellbash.vm.box = "generic/rhel9"
	shellbash.vm.network "private_network", ip: "192.168.56.90"
	shellbash.vm.provider "virtualbox" do |vb|
    config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
    end
   end
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "generic/rhel9"
	node01.vm.network "private_network", ip: "192.168.56.91"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512 
        v.cpus = 1
     end
  end
  
  config.vm.define "node02" do |node02|
    node02.vm.box = "generic/rhel9"
	node02.vm.network "private_network", ip: "192.168.56.92"
     config.vm.provider "virtualbox" do |v|
        v.memory = 512 
        v.cpus = 1
     end
  end

   config.vm.define "node03" do |node03|
    node03.vm.box = "generic/rhel9"
        node03.vm.network "private_network", ip: "192.168.56.93"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 2
     end
  end


end

