Vagrant.configure("2") do |config|

  config.vm.define "ansible-c" do |ansible|
    ansible.vm.box = "generic/rhel9"
	ansible.vm.network "private_network", ip: "192.168.56.70"
	ansible.vm.provider "virtualbox" do |vb|
    config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
    end
   end
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "generic/rhel9"
	node01.vm.network "private_network", ip: "192.168.56.71"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512 
        v.cpus = 1
     end
  end
  
  config.vm.define "node02" do |node02|
    node02.vm.box = "generic/rhel9"
	node02.vm.network "private_network", ip: "192.168.56.72"
     config.vm.provider "virtualbox" do |v|
        v.memory = 512 
        v.cpus = 1
     end
  end

   config.vm.define "node03" do |node03|
    node03.vm.box = "generic/rhel9"
        node03.vm.network "private_network", ip: "192.168.56.73"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 2
     end
  end

  config.vm.define "node04" do |node04|
    node04.vm.box = "generic/rhel9"
	node04.vm.network "private_network", ip: "192.168.56.74"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 1
     end
  end

  config.vm.define "node05" do |node05|
    node05.vm.box = "generic/rhel9"
	node05.vm.network "private_network", ip: "192.168.56.75"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 1
     end
  end

  config.vm.define "ubuntu06" do |ubuntu06|
    ubuntu06.vm.box = "bento/ubuntu-20.04"
        ubuntu06.vm.network "private_network", ip: "192.168.56.76"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 1
     end
  end


  config.vm.define "shell" do |shell|
    shell.vm.box = "centos/7"
        shell.vm.network "private_network", ip: "192.168.56.77"
     shell.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 1
     end
  end

  config.vm.define "nfsserver" do |nfsserver|
    nfsserver.vm.box = "generic/rhel9"
        nfsserver.vm.network "private_network", ip: "192.168.56.78"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end

  config.vm.define "nfs-client01" do |nisserver|
    nisserver.vm.box = "generic/rhel9"
        nisserver.vm.network "private_network", ip: "192.168.56.79"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end

  config.vm.define "nfs-client02" do |nisserver|
    nisserver.vm.box = "generic/rhel9"
        nisserver.vm.network "private_network", ip: "192.168.56.80"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end

  config.vm.define "nisserver-master" do |nisserver|
    nisserver.vm.box = "generic/rhel9"
        nisserver.vm.network "private_network", ip: "192.168.56.81"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end

  config.vm.define "nisserver-slave" do |nisserver|
    nisserver.vm.box = "generic/rhel9"
        nisserver.vm.network "private_network", ip: "192.168.56.82"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end

  config.vm.define "nisserver-client" do |nisserver|
    nisserver.vm.box = "generic/rhel9"
        nisserver.vm.network "private_network", ip: "192.168.56.83"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
     end
  end
end
