#Vagrant.configure("2") do |config|

#  config.vm.define "lvm" do |lvm|
#    lvm.vm.box = "generic/rhel9"
#        lvm.vm.network "private_network", ip: "192.168.56.81"
#        lvm.vm.provider "virtualbox" do |vb|
#        lvm.vm.disk :disk, size: "30GB", name: "extra_storage1"
#        lvm.vm.disk :disk, size: "30GB", name: "extra_storage2"
#    config.vm.provider "virtualbox" do |v|
#       v.memory = 2048
#       v.cpus = 2
#    end
#   end
#end
#end


Vagrant.configure("2") do |config|
 config.vm.define "lvm" do |lvm|
 config.vm.box = "generic/rhel9"
 config.vm.network "private_network", ip: "192.168.56.81"
      

  config.vm.provider :virtualbox

  config.vm.disk :disk, size: "30GB", name: "extra_storage1"
  config.vm.disk :disk, size: "30GB", name: "extra_storage2"
  config.vm.disk :disk, size: "30GB", name: "extra_storage3"
  config.vm.disk :disk, size: "30GB", name: "extra_storage4"
end
end
