Vagrant.configure("2") do |config|
 config.vm.define "lvm" do |lvm|
 config.vm.box = "generic/rhel9"
 config.vm.network "private_network", ip: "192.168.56.81"
 config.vm.network "private_network", ip: "192.168.56.82"
 config.vm.network "private_network", ip: "192.168.56.83"
 config.vm.network "private_network", ip: "192.168.56.84"
# config.vm.network "private_network", ip: "192.168.56.85"
      

  config.vm.provider :virtualbox

  config.vm.disk :disk, size: "30GB", name: "extra_storage1"
  config.vm.disk :disk, size: "30GB", name: "extra_storage2"
  config.vm.disk :disk, size: "30GB", name: "extra_storage3"
  config.vm.disk :disk, size: "30GB", name: "extra_storage4"
end
end

Vagrant.configure("2") do |config|
 config.vm.define "client" do |client|
 config.vm.box = "generic/rhel9"
 config.vm.network "private_network", ip: "192.168.56.85"
# config.vm.network "private_network", ip: "192.168.56.83"
# config.vm.network "private_network", ip: "192.168.56.84"
# config.vm.network "private_network", ip: "192.168.56.85"
      

#  config.vm.provider :virtualbox

#  config.vm.disk :disk, size: "30GB", name: "extra_storage1"
#  config.vm.disk :disk, size: "30GB", name: "extra_storage2"
#  config.vm.disk :disk, size: "30GB", name: "extra_storage3"
#  config.vm.disk :disk, size: "30GB", name: "extra_storage4"
end
end


