Vagrant.configure("2") do |config|

  config.vm.define "bootissue" do |bootissue|
    bootissue.vm.box = "generic/rhel9"
        bootissue.vm.network "private_network", ip: "192.168.56.80"
        bootissue.vm.provider "virtualbox" do |vb|
    config.vm.provider "virtualbox" do |v|
       v.memory = 2048
       v.cpus = 2
    end
   end
end
end
