Vagrant.configure("2") do |config|

  config.vm.define "yum" do |yum|
    yum.vm.box = "generic/rhel9"
	yum.vm.network "private_network", ip: "192.168.56.80"
	yum.vm.provider "virtualbox" do |vb|
    config.vm.provider "virtualbox" do |v|
       v.gui = true
       v.memory = 2048
       v.cpus = 2
    end
   end
  end

  config.vm.define "client01" do |client01|
    client01.vm.box = "generic/rhel9"
	client01.vm.network "private_network", ip: "192.168.56.81"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 1
     end
  end

  config.vm.define "client02" do |client02|
    client02.vm.box = "generic/rhel9"
	client02.vm.network "private_network", ip: "192.168.56.82"
     config.vm.provider "virtualbox" do |v|
        v.memory = 1048
        v.cpus = 1
     end
  end


end


